name: Extract Traffic Data

on:
  schedule:
    - cron: '0 5,11,18,21,0 * * *'  # Schedule for 2am, 8am, 3pm, 6pm, 9pm GMT-3 (which is 5, 11, 18, 21, 0 UTC)
  workflow_dispatch:

jobs:
  extract_traffic_data:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Check out repository
        uses: actions/checkout@v3  # Updated to the latest version

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to the latest version
        with:
          python-version: '3.9'

      # Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run the traffic data extraction script
      - name: Extract traffic data
        env:
          HERE_API_KEY: ${{ secrets.HERE_API_KEY }}
        run: |
          python your_script_name.py  # Replace with the actual name of your script

      # Configure Git to push changes back to the repository
      - name: Configure Git credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      # Commit and push the generated geopackage file to the repository
      - name: Commit and push geopackage file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add output.gpkg
          git commit -m "Add generated geopackage file with traffic data"
          git push
