name: Traffic Data Collection
on:
  schedule:
    - cron: '0 2 * * *'  # 2 AM UTC
    - cron: '0 8 * * *'  # 8 AM UTC
    - cron: '0 15 * * *' # 3 PM UTC
    - cron: '0 18 * * *' # 6 PM UTC
    - cron: '0 21 * * *' # 9 PM UTC
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run traffic data script
        env:
          API_KEY: ${{ secrets.HERE_API_KEY }}
        run: |
          python here_extract.py
