name: Extract Traffic Data and Save to GPKG

on:
  schedule:
    - cron: "0 5,11,18,21,0 * * *" # Times converted to UTC (5am, 11am, 6pm, 9pm, and midnight GMT-3)
    
jobs:
  extract_traffic_data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Traffic Data Extraction
        env:
          API_KEY: ${{ secrets.HERE_API_KEY }}
        run: |
          python extract_traffic_here.py

      - name: Commit and Push Results
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git add *.gpkg
          git commit -m "Add new traffic data"
          git push
